# Generated by Django 6.0.2 on 2026-02-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meno', models.CharField(max_length=100)),
                ('hp', models.IntegerField(default=100)),
                ('max_hp', models.IntegerField(default=100)),
                ('sila', models.IntegerField(default=20)),
                ('level', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('obrana', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('typ', models.CharField(choices=[('zbran', 'Zbraň'), ('brnenie', 'Brnenie'), ('lektvar', 'Lektvár')], default='lektvar', max_length=20)),
                ('bonus_hp', models.IntegerField(default=0)),
                ('bonus_sila', models.IntegerField(default=0)),
                ('bonus_obrana', models.IntegerField(default=0)),
                ('majitel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batoh', to='game.postava')),
            ],
        ),
    ]
