# Generated by Django 6.0.2 on 2026-02-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nepriatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=100)),
                ('sila', models.IntegerField(default=10)),
                ('hp', models.IntegerField(default=50)),
                ('xp_odmena', models.IntegerField(default=20)),
            ],
        ),
    ]
