# Generated by Django 6.0.2 on 2026-02-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmet',
            old_name='hp',
            new_name='bonus_hp',
        ),
        migrations.RenameField(
            model_name='predmet',
            old_name='sila_bonus',
            new_name='bonus_sila',
        ),
        migrations.RenameField(
            model_name='predmet',
            old_name='meno',
            new_name='nazov',
        ),
        migrations.AddField(
            model_name='predmet',
            name='majitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predmety', to='game.postava'),
        ),
    ]
