# Generated by Django 6.0.2 on 2026-02-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_nepriatel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nepriatel',
            name='ikona',
            field=models.CharField(default='⚔', max_length=50),
        ),
    ]
