# Generated by Django 6.0.2 on 2026-02-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_nepriatel_ikona'),
    ]

    operations = [
        migrations.AddField(
            model_name='postava',
            name='zlato',
            field=models.IntegerField(default=0),
        ),
    ]
