# Generated by Django 6.0.2 on 2026-02-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_postava_zlato'),
    ]

    operations = [
        migrations.AddField(
            model_name='postava',
            name='xp_na_level',
            field=models.IntegerField(default=0),
        ),
    ]
