# Generated by Django 6.0.2 on 2026-02-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_postava_xp_na_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='postava',
            name='max_sloty_batohu',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='predmet',
            name='rarity',
            field=models.CharField(choices=[('common', 'Obyčajný'), ('rare', 'Vzácny'), ('legendary', 'Legendárny')], default='common', max_length=20),
        ),
        migrations.AlterField(
            model_name='postava',
            name='xp_na_level',
            field=models.IntegerField(default=100),
        ),
    ]
