# Generated by Django 6.0.2 on 2026-02-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_postava_max_sloty_batohu_predmet_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postava',
            name='quest_level_splneny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postava',
            name='quest_sila_splneny',
            field=models.BooleanField(default=False),
        ),
    ]
