# Generated by Django 4.2.1 on 2026-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_postava_pouzivatel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nepriatel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='typ',
            field=models.CharField(choices=[('zbran', 'Zbraň'), ('stit', 'Štít'), ('brnenie', 'Brnenie'), ('prsten', 'Prsteň'), ('lektvar', 'Lektvár')], default='lektvar', max_length=20),
        ),
    ]
