# Generated by Django 4.2.1 on 2026-04-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_nepriatel_id_alter_postava_id_alter_predmet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predmet',
            name='nasadene',
            field=models.BooleanField(default=False),
        ),
    ]
