# Generated by Django 6.0.2 on 2026-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_predmet_nasadene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postava',
            old_name='max_sloty_batohu',
            new_name='kapacita_batohu',
        ),
        migrations.AlterField(
            model_name='nepriatel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postava',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
